export { detectManager, listLockFiles } from "./detector";
export type { PackageManager } from "./detector";
export { readProjectConfig, writeProjectConfig, readLocalConfig, writeLocalConfig, } from "./config";
export type { ProjectConfig, LocalConfig } from "./config";
export { execute } from "./executor";
export { syncLockFile, getLockFileName, getNonCanonicalLockFiles } from "./sync";
export { pinVersions } from "./pinner";
export { installHooks, uninstallHooks } from "./hooks";
export { resolveFromNodeModules } from "./lockfile/resolver";
export type { ResolvedPackage, DependencyGraph } from "./lockfile/types";
