"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.resolveFromNodeModules = exports.uninstallHooks = exports.installHooks = exports.pinVersions = exports.getNonCanonicalLockFiles = exports.getLockFileName = exports.syncLockFile = exports.execute = exports.writeLocalConfig = exports.readLocalConfig = exports.writeProjectConfig = exports.readProjectConfig = exports.listLockFiles = exports.detectManager = void 0;
var detector_1 = require("./detector");
Object.defineProperty(exports, "detectManager", { enumerable: true, get: function () { return detector_1.detectManager; } });
Object.defineProperty(exports, "listLockFiles", { enumerable: true, get: function () { return detector_1.listLockFiles; } });
var config_1 = require("./config");
Object.defineProperty(exports, "readProjectConfig", { enumerable: true, get: function () { return config_1.readProjectConfig; } });
Object.defineProperty(exports, "writeProjectConfig", { enumerable: true, get: function () { return config_1.writeProjectConfig; } });
Object.defineProperty(exports, "readLocalConfig", { enumerable: true, get: function () { return config_1.readLocalConfig; } });
Object.defineProperty(exports, "writeLocalConfig", { enumerable: true, get: function () { return config_1.writeLocalConfig; } });
var executor_1 = require("./executor");
Object.defineProperty(exports, "execute", { enumerable: true, get: function () { return executor_1.execute; } });
var sync_1 = require("./sync");
Object.defineProperty(exports, "syncLockFile", { enumerable: true, get: function () { return sync_1.syncLockFile; } });
Object.defineProperty(exports, "getLockFileName", { enumerable: true, get: function () { return sync_1.getLockFileName; } });
Object.defineProperty(exports, "getNonCanonicalLockFiles", { enumerable: true, get: function () { return sync_1.getNonCanonicalLockFiles; } });
var pinner_1 = require("./pinner");
Object.defineProperty(exports, "pinVersions", { enumerable: true, get: function () { return pinner_1.pinVersions; } });
var hooks_1 = require("./hooks");
Object.defineProperty(exports, "installHooks", { enumerable: true, get: function () { return hooks_1.installHooks; } });
Object.defineProperty(exports, "uninstallHooks", { enumerable: true, get: function () { return hooks_1.uninstallHooks; } });
var resolver_1 = require("./lockfile/resolver");
Object.defineProperty(exports, "resolveFromNodeModules", { enumerable: true, get: function () { return resolver_1.resolveFromNodeModules; } });
