"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const node_test_1 = require("node:test");
const strict_1 = __importDefault(require("node:assert/strict"));
const npm_1 = require("../src/lockfile/npm");
const yarn_1 = require("../src/lockfile/yarn");
const pnpm_1 = require("../src/lockfile/pnpm");
const bun_1 = require("../src/lockfile/bun");
// ── Test fixtures ──────────────────────────────────────────────────
function createTestGraph() {
    const graph = new Map();
    graph.set("node_modules/express", {
        name: "express",
        version: "4.21.0",
        resolved: "https://registry.npmjs.org/express/-/express-4.21.0.tgz",
        integrity: "sha512-VqcNGcj/Id5ZT1LZ/cfihi3ttTn+NJmkli2eZAGUUYBhQ==",
        dev: false,
        dependencies: { accepts: "~1.3.8", "body-parser": "1.20.3" },
        engines: { node: ">= 0.10.0" },
    });
    graph.set("node_modules/accepts", {
        name: "accepts",
        version: "1.3.8",
        resolved: "https://registry.npmjs.org/accepts/-/accepts-1.3.8.tgz",
        integrity: "sha512-PYAthTa2m2VKxuvSD3DPC/Gy+U+sOA1LAuT8mkmRuvw==",
        dev: false,
        dependencies: { "mime-types": "~2.1.34", negotiator: "0.6.3" },
    });
    graph.set("node_modules/typescript", {
        name: "typescript",
        version: "5.4.5",
        resolved: "https://registry.npmjs.org/typescript/-/typescript-5.4.5.tgz",
        integrity: "sha512-vcI4UpRgg81oIRUFwR0WSIHKt11nJ7SAVlQ==",
        dev: true,
        bin: { tsc: "bin/tsc", tsserver: "bin/tsserver" },
        engines: { node: ">=14.17" },
    });
    return graph;
}
function createTestRootPkg() {
    return {
        name: "test-project",
        version: "1.0.0",
        dependencies: { express: "4.21.0" },
        devDependencies: { typescript: "5.4.5" },
    };
}
// ── npm ────────────────────────────────────────────────────────────
(0, node_test_1.describe)("npm lock file", () => {
    (0, node_test_1.it)("generates valid package-lock.json", () => {
        const graph = createTestGraph();
        const rootPkg = createTestRootPkg();
        const output = npm_1.npmGenerator.generate(graph, rootPkg);
        const parsed = JSON.parse(output);
        strict_1.default.equal(parsed.lockfileVersion, 3);
        strict_1.default.equal(parsed.requires, true);
        strict_1.default.ok(parsed.packages[""]);
        strict_1.default.equal(parsed.packages[""].name, "test-project");
        strict_1.default.equal(parsed.packages["node_modules/express"].version, "4.21.0");
        strict_1.default.equal(parsed.packages["node_modules/typescript"].dev, true);
        strict_1.default.equal(parsed.packages["node_modules/accepts"].version, "1.3.8");
    });
    (0, node_test_1.it)("round-trips through parser", () => {
        const graph = createTestGraph();
        const rootPkg = createTestRootPkg();
        const output = npm_1.npmGenerator.generate(graph, rootPkg);
        const reparsed = npm_1.npmParser.parse(output);
        strict_1.default.equal(reparsed.size, 3);
        strict_1.default.equal(reparsed.get("node_modules/express")?.version, "4.21.0");
        strict_1.default.equal(reparsed.get("node_modules/typescript")?.dev, true);
        strict_1.default.equal(reparsed.get("node_modules/accepts")?.version, "1.3.8");
    });
    (0, node_test_1.it)("includes resolved URLs and integrity hashes", () => {
        const graph = createTestGraph();
        const output = npm_1.npmGenerator.generate(graph, createTestRootPkg());
        const parsed = JSON.parse(output);
        const expr = parsed.packages["node_modules/express"];
        strict_1.default.ok(expr.resolved?.includes("registry.npmjs.org"));
        strict_1.default.ok(expr.integrity?.startsWith("sha512-"));
    });
    (0, node_test_1.it)("sorts packages deterministically", () => {
        const graph = createTestGraph();
        const output = npm_1.npmGenerator.generate(graph, createTestRootPkg());
        const parsed = JSON.parse(output);
        const keys = Object.keys(parsed.packages).filter((k) => k !== "");
        const sorted = [...keys].sort();
        strict_1.default.deepEqual(keys, sorted);
    });
});
// ── yarn ───────────────────────────────────────────────────────────
(0, node_test_1.describe)("yarn lock file", () => {
    (0, node_test_1.it)("generates yarn.lock with header", () => {
        const graph = createTestGraph();
        const output = yarn_1.yarnGenerator.generate(graph, createTestRootPkg());
        strict_1.default.ok(output.startsWith("# THIS IS AN AUTOGENERATED FILE"));
        strict_1.default.ok(output.includes("# yarn lockfile v1"));
    });
    (0, node_test_1.it)("generates entries with version, resolved, integrity", () => {
        const graph = createTestGraph();
        const output = yarn_1.yarnGenerator.generate(graph, createTestRootPkg());
        strict_1.default.ok(output.includes('version "4.21.0"'));
        strict_1.default.ok(output.includes("resolved \"https://registry.npmjs.org/express/"));
        strict_1.default.ok(output.includes("integrity sha512-"));
    });
    (0, node_test_1.it)("includes dependencies sub-section", () => {
        const graph = createTestGraph();
        const output = yarn_1.yarnGenerator.generate(graph, createTestRootPkg());
        strict_1.default.ok(output.includes("dependencies:"));
        strict_1.default.ok(output.includes('accepts "~1.3.8"'));
    });
    (0, node_test_1.it)("round-trips through parser", () => {
        const graph = createTestGraph();
        const rootPkg = createTestRootPkg();
        const output = yarn_1.yarnGenerator.generate(graph, rootPkg);
        const reparsed = yarn_1.yarnParser.parse(output);
        strict_1.default.ok(reparsed.has("node_modules/express"));
        strict_1.default.equal(reparsed.get("node_modules/express")?.version, "4.21.0");
        strict_1.default.ok(reparsed.has("node_modules/accepts"));
        strict_1.default.ok(reparsed.has("node_modules/typescript"));
    });
});
// ── pnpm ───────────────────────────────────────────────────────────
(0, node_test_1.describe)("pnpm lock file", () => {
    (0, node_test_1.it)("generates pnpm-lock.yaml with header", () => {
        const graph = createTestGraph();
        const output = pnpm_1.pnpmGenerator.generate(graph, createTestRootPkg());
        strict_1.default.ok(output.includes("lockfileVersion: '9.0'"));
        strict_1.default.ok(output.includes("importers:"));
        strict_1.default.ok(output.includes("packages:"));
    });
    (0, node_test_1.it)("includes importers section with root dependencies", () => {
        const graph = createTestGraph();
        const output = pnpm_1.pnpmGenerator.generate(graph, createTestRootPkg());
        strict_1.default.ok(output.includes("dependencies:"));
        strict_1.default.ok(output.includes("express:"));
        strict_1.default.ok(output.includes("specifier: 4.21.0"));
        strict_1.default.ok(output.includes("devDependencies:"));
        strict_1.default.ok(output.includes("typescript:"));
    });
    (0, node_test_1.it)("includes package entries with resolution", () => {
        const graph = createTestGraph();
        const output = pnpm_1.pnpmGenerator.generate(graph, createTestRootPkg());
        strict_1.default.ok(output.includes("'express@4.21.0':"));
        strict_1.default.ok(output.includes("resolution: {integrity: sha512-"));
    });
    (0, node_test_1.it)("marks dev packages", () => {
        const graph = createTestGraph();
        const output = pnpm_1.pnpmGenerator.generate(graph, createTestRootPkg());
        // typescript should have dev: true
        const tsSection = output.substring(output.indexOf("'typescript@5.4.5':"));
        strict_1.default.ok(tsSection.includes("dev: true"));
    });
    (0, node_test_1.it)("round-trips through parser", () => {
        const graph = createTestGraph();
        const rootPkg = createTestRootPkg();
        const output = pnpm_1.pnpmGenerator.generate(graph, rootPkg);
        const reparsed = pnpm_1.pnpmParser.parse(output);
        strict_1.default.ok(reparsed.has("node_modules/express"));
        strict_1.default.equal(reparsed.get("node_modules/express")?.version, "4.21.0");
        strict_1.default.ok(reparsed.has("node_modules/typescript"));
        strict_1.default.equal(reparsed.get("node_modules/typescript")?.dev, true);
    });
});
// ── bun ────────────────────────────────────────────────────────────
(0, node_test_1.describe)("bun lock file", () => {
    (0, node_test_1.it)("generates valid JSON", () => {
        const graph = createTestGraph();
        const output = bun_1.bunGenerator.generate(graph, createTestRootPkg());
        const parsed = JSON.parse(output);
        strict_1.default.equal(parsed.lockfileVersion, 0);
        strict_1.default.ok(parsed.workspaces);
        strict_1.default.ok(parsed.packages);
    });
    (0, node_test_1.it)("includes root workspace", () => {
        const graph = createTestGraph();
        const output = bun_1.bunGenerator.generate(graph, createTestRootPkg());
        const parsed = JSON.parse(output);
        const root = parsed.workspaces[""];
        strict_1.default.equal(root.name, "test-project");
        strict_1.default.deepEqual(root.dependencies, { express: "4.21.0" });
        strict_1.default.deepEqual(root.devDependencies, { typescript: "5.4.5" });
    });
    (0, node_test_1.it)("includes packages as tuples", () => {
        const graph = createTestGraph();
        const output = bun_1.bunGenerator.generate(graph, createTestRootPkg());
        const parsed = JSON.parse(output);
        strict_1.default.ok(Array.isArray(parsed.packages.express));
        strict_1.default.equal(parsed.packages.express[0], "express@4.21.0");
    });
    (0, node_test_1.it)("round-trips through parser", () => {
        const graph = createTestGraph();
        const rootPkg = createTestRootPkg();
        const output = bun_1.bunGenerator.generate(graph, rootPkg);
        const reparsed = bun_1.bunParser.parse(output);
        strict_1.default.ok(reparsed.has("node_modules/express"));
        strict_1.default.equal(reparsed.get("node_modules/express")?.version, "4.21.0");
        strict_1.default.ok(reparsed.has("node_modules/typescript"));
    });
});
