"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.yarnParser = exports.yarnGenerator = void 0;
/**
 * Generate and parse yarn.lock (v1 format).
 *
 * Format:
 *   # yarn lockfile v1
 *
 *   package@range:
 *     version "1.0.0"
 *     resolved "https://registry..."
 *     integrity "sha512-..."
 *     dependencies:
 *       dep "^1.0.0"
 */
exports.yarnGenerator = {
    generate(graph, rootPkg) {
        const lines = [
            "# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.",
            "# yarn lockfile v1",
            "",
            "",
        ];
        // Build a map: packageName → { version, resolved, integrity, deps }
        // We need to match packages to the ranges declared in root package.json
        const allRootDeps = {
            ...rootPkg.dependencies,
            ...rootPkg.devDependencies,
            ...rootPkg.optionalDependencies,
        };
        // Group by name+version (multiple ranges can resolve to same version)
        const entryMap = new Map();
        const sortedKeys = [...graph.keys()].sort();
        for (const key of sortedKeys) {
            const pkg = graph.get(key);
            // Only include top-level node_modules entries for yarn.lock v1
            // (nested deps are flattened in yarn v1)
            if (key.indexOf("node_modules", "node_modules/".length) !== -1)
                continue;
            const entryKey = `${pkg.name}@${pkg.version}`;
            const existing = entryMap.get(entryKey);
            if (existing) {
                // Add additional range if we know it
                const rootRange = allRootDeps[pkg.name];
                if (rootRange && !existing.ranges.includes(rootRange)) {
                    existing.ranges.push(rootRange);
                }
                continue;
            }
            const ranges = [];
            const rootRange = allRootDeps[pkg.name];
            if (rootRange) {
                ranges.push(rootRange);
            }
            else {
                // For transitive deps, use the version as the range
                ranges.push(pkg.version);
            }
            entryMap.set(entryKey, {
                name: pkg.name,
                ranges,
                version: pkg.version,
                resolved: pkg.resolved,
                integrity: pkg.integrity,
                dependencies: pkg.dependencies,
                optionalDependencies: pkg.optionalDependencies,
            });
        }
        // Sort entries alphabetically by name
        const sorted = [...entryMap.values()].sort((a, b) => a.name.localeCompare(b.name));
        for (const entry of sorted) {
            // Header: "pkg@range, pkg@range2:"
            const rangeKeys = entry.ranges.map((r) => `${entry.name}@${r}`);
            const header = rangeKeys.map((k) => quoteIfNeeded(k)).join(", ");
            lines.push(`${header}:`);
            lines.push(`  version "${entry.version}"`);
            if (entry.resolved) {
                lines.push(`  resolved "${entry.resolved}"`);
            }
            if (entry.integrity) {
                lines.push(`  integrity ${entry.integrity}`);
            }
            if (entry.dependencies && Object.keys(entry.dependencies).length > 0) {
                lines.push("  dependencies:");
                const sortedDeps = Object.entries(entry.dependencies).sort(([a], [b]) => a.localeCompare(b));
                for (const [dep, range] of sortedDeps) {
                    lines.push(`    ${quoteIfNeeded(dep)} "${range}"`);
                }
            }
            if (entry.optionalDependencies && Object.keys(entry.optionalDependencies).length > 0) {
                lines.push("  optionalDependencies:");
                const sortedDeps = Object.entries(entry.optionalDependencies).sort(([a], [b]) => a.localeCompare(b));
                for (const [dep, range] of sortedDeps) {
                    lines.push(`    ${quoteIfNeeded(dep)} "${range}"`);
                }
            }
            lines.push("");
        }
        return lines.join("\n");
    },
};
exports.yarnParser = {
    parse(content) {
        const graph = new Map();
        const lines = content.split("\n");
        let currentName = "";
        let current = {};
        let inDeps = false;
        let depsField = "";
        function flushCurrent() {
            if (!currentName)
                return;
            const name = currentName;
            graph.set(`node_modules/${name}`, {
                name,
                version: current.version ?? "0.0.0",
                resolved: current.resolved,
                integrity: current.integrity,
                dev: false,
                dependencies: current.dependencies,
                optionalDependencies: current.optionalDependencies,
            });
            currentName = "";
            current = {};
            inDeps = false;
        }
        for (const line of lines) {
            // Skip comments and empty lines
            if (line.startsWith("#") || line.trim() === "") {
                if (line.trim() === "" && currentName) {
                    flushCurrent();
                }
                continue;
            }
            // Header line: "pkg@range:" or "pkg@range, pkg@range2:"
            if (!line.startsWith(" ")) {
                flushCurrent();
                // Extract package name from "pkg@range:" or "@scope/pkg@range:"
                const headerClean = line.replace(/:$/, "").trim();
                const firstEntry = headerClean.split(",")[0].trim().replace(/^"/, "").replace(/"$/, "");
                // Find last @ that isn't at position 0 (scoped package)
                const atIdx = firstEntry.lastIndexOf("@");
                if (atIdx > 0) {
                    currentName = firstEntry.substring(0, atIdx);
                }
                else {
                    currentName = firstEntry;
                }
                current = {};
                inDeps = false;
                continue;
            }
            // Indented lines — inside an entry
            const trimmed = line.trimStart();
            // Sub-section headers: "dependencies:" or "optionalDependencies:"
            if (trimmed === "dependencies:" || trimmed === "optionalDependencies:") {
                inDeps = true;
                depsField = trimmed.replace(":", "");
                if (!current[depsField])
                    current[depsField] = {};
                continue;
            }
            // Dependency entries (4-space indent): `    pkg "range"`
            if (inDeps && line.startsWith("    ")) {
                const depMatch = trimmed.match(/^"?([^"\s]+)"?\s+"([^"]+)"$/);
                if (depMatch) {
                    const deps = current[depsField];
                    deps[depMatch[1]] = depMatch[2];
                }
                continue;
            }
            // Key-value pairs (2-space indent): `  version "1.0.0"`
            inDeps = false;
            const kvMatch = trimmed.match(/^(\w+)\s+"?([^"]*)"?$/);
            if (kvMatch) {
                current[kvMatch[1]] = kvMatch[2];
            }
        }
        flushCurrent();
        return graph;
    },
};
function quoteIfNeeded(s) {
    // Quote if contains @, /, or special chars
    if (s.includes("@") || s.includes("/")) {
        return `"${s}"`;
    }
    return s;
}
